#!/bin/bash
TARGET="sky"
COOJA_BUILD=1
SDN_WISE_DEBUG=1
TRICKLE_ON=0
TRICKLE_DEBUG=0
SEND_DATA=1
DATA_REPLY=1
BATTERY_ENABLED=0

mkdir cooja_firmwares

make TARGET=$TARGET DEFINES=COOJA=$COOJA_BUILD,SINK=1,SDN_WISE_DEBUG=$SDN_WISE_DEBUG,TRICKLE_ON=$TRICKLE_ON,TRICKLE_DEBUG=$TRICKLE_DEBUG,SEND_DATA=$SEND_DATA,DATA_REPLY=$DATA_REPLY
mv sdn-wise.$TARGET cooja_firmwares/sink.$TARGET 
make TARGET=$TARGET clean

make TARGET=$TARGET DEFINES=COOJA=$COOJA_BUILD,SINK=0,SDN_WISE_DEBUG=$SDN_WISE_DEBUG,TRICKLE_ON=$TRICKLE_ON,TRICKLE_DEBUG=$TRICKLE_DEBUG,SEND_DATA=$SEND_DATA,DATA_REPLY=$DATA_REPLY
mv sdn-wise.$TARGET cooja_firmwares/node.$TARGET 
make TARGET=$TARGET clean


